/**
 * Wiktionary comparison tests for verb-forms.js
 *
 * Tests computeConjugation() against conjugation tables extracted
 * directly from the German Wiktionary (de-extract.jsonl).
 *
 * Fixtures: tests/fixtures/wiktionary-verbs.json (77 verbs)
 * Generated by: scripts/extract-verb-fixtures.js
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { computeConjugation } from "../src/utils/verb-forms.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const endings = JSON.parse(
  readFileSync(join(ROOT, "data/rules/verb-endings.json"), "utf-8"),
);
const fixtures = JSON.parse(
  readFileSync(join(ROOT, "tests/fixtures/wiktionary-verbs.json"), "utf-8"),
);

// ============================================================
// Expected failures — verbs that our rules-based engine cannot
// handle without special-case code. Documented here so the test
// suite stays green while clearly showing what's not covered.
// ============================================================

/**
 * Truly irregular verbs — their conjugation patterns don't follow
 * any regular class (weak/strong/mixed). These are stored as
 * conjugation_class: "irregular" in actual word files with full
 * conjugation tables. computeConjugation returns stored forms as-is.
 * Tested separately below to verify the passthrough works.
 */
const TRULY_IRREGULAR = new Set([
  "sein",     // bin/bist/ist — completely suppletive
  "haben",    // hast/hat — irregular present
  "werden",   // wirst/wird — irregular present
  "wissen",   // weiß/weißt — praeteritopraesentia
  "können",   // kann/kannst — modal
  "müssen",   // muss/musst — modal
  "sollen",   // soll/sollst — modal
  "wollen",   // will/willst — modal
  "dürfen",   // darf/darfst — modal
  "mögen",    // mag/magst — modal
]);

/**
 * Weak imperative -e elision — Wiktionary prefers the short form
 * (kauf!, hör!) while our engine produces the full form (kaufe!, höre!).
 * Both are grammatically correct in modern German.
 */
const IMPERATIVE_E_ELISION = new Set([
  "kaufen",   // kaufe! vs kauf!
  "hören",    // höre! vs hör!
  "reden",    // rede! vs red!
  "sagen",    // sage! vs sag!
  "glauben",  // glaube! vs glaub!
  "fragen",   // frage! vs frag!
  "spielen",  // spiele! vs spiel!
]);

/**
 * Other individual edge cases not yet handled by the engine.
 */
const OTHER_KNOWN_ISSUES = new Set([
  "wechseln", // imperative: wechsle! vs wechsele! (Wiktionary uses long form)
  "kennen",   // imperative: kenn! vs kenne! (Wiktionary uses long form)
  "einladen", // present.du: lädest ein vs lädst ein (e-insertion + vowel change interaction)
]);

const ALL_EXPECTED_FAILURES = new Set([
  ...IMPERATIVE_E_ELISION,
  ...OTHER_KNOWN_ISSUES,
]);

// ============================================================
// Helpers
// ============================================================

/**
 * Build a verb input object for computeConjugation.
 * For truly irregular verbs, passes conjugation_class: "irregular"
 * with the Wiktionary table as stored conjugation (matching how
 * actual word files store them).
 */
function buildVerbInput(word, f) {
  if (TRULY_IRREGULAR.has(word)) {
    return {
      word: f.word,
      conjugation_class: "irregular",
      conjugation: f.wiktionary,
      separable: f.separable,
      prefix: f.prefix,
    };
  }
  return {
    word: f.word,
    conjugation_class: f.conjugation_class,
    stems: f.stems,
    past_participle: f.past_participle,
    separable: f.separable,
    prefix: f.prefix,
  };
}

/**
 * Compare computed conjugation against Wiktionary forms.
 * Skips cells listed in `skipCells` (e.g., "subjunctive2.ich")
 * which are known Wiktionary-internal inconsistencies detected
 * by the majority-vote stem extraction.
 */
function compareTenses(computed, wiktionary, skipCells = []) {
  const skip = new Set(skipCells);
  const mismatches = [];
  const tenses = ["present", "preterite", "subjunctive1", "subjunctive2"];

  for (const tense of tenses) {
    for (const [person, form] of Object.entries(wiktionary[tense] || {})) {
      if (skip.has(`${tense}.${person}`)) continue;
      if (form && computed[tense]?.[person] !== form) {
        mismatches.push(
          `${tense}.${person}: "${computed[tense]?.[person]}" vs "${form}"`,
        );
      }
    }
  }

  for (const [person, form] of Object.entries(wiktionary.imperative || {})) {
    if (skip.has(`imperative.${person}`)) continue;
    if (form && computed.imperative?.[person] !== form) {
      mismatches.push(
        `imperative.${person}: "${computed.imperative?.[person]}" vs "${form}"`,
      );
    }
  }

  if (wiktionary.participle1 && computed.participle1 !== wiktionary.participle1) {
    mismatches.push(
      `participle1: "${computed.participle1}" vs "${wiktionary.participle1}"`,
    );
  }
  if (wiktionary.participle2 && computed.participle2 !== wiktionary.participle2) {
    mismatches.push(
      `participle2: "${computed.participle2}" vs "${wiktionary.participle2}"`,
    );
  }

  return mismatches;
}

// ============================================================
// Tests: verbs that should pass (including irregular + sibilant)
// ============================================================

describe("Wiktionary comparison — passing verbs", () => {
  const passingVerbs = Object.entries(fixtures).filter(
    ([word]) => !ALL_EXPECTED_FAILURES.has(word),
  );

  it.each(passingVerbs)("%s — matches Wiktionary forms", (word, f) => {
    const verb = buildVerbInput(word, f);
    const computed = computeConjugation(verb, endings);
    const mismatches = compareTenses(computed, f.wiktionary, f.inconsistent_cells || []);
    expect(mismatches, mismatches.join("; ")).toEqual([]);
  });
});

// ============================================================
// Tests: documented expected failures
// ============================================================

describe("Wiktionary comparison — expected failures (documented)", () => {
  describe("weak imperative -e elision (both forms are correct)", () => {
    for (const word of IMPERATIVE_E_ELISION) {
      it(`${word} — mismatch is only in imperative.du`, () => {
        const f = fixtures[word];
        if (!f?.stems) return;
        const verb = buildVerbInput(word, f);
        const computed = computeConjugation(verb, endings);
        const mismatches = compareTenses(computed, f.wiktionary);
        // Should only disagree on imperative
        expect(mismatches.length).toBe(1);
        expect(mismatches[0]).toContain("imperative.du");
      });
    }
  });

  describe("other individual edge cases", () => {
    it("wechseln — imperative uses long form in Wiktionary", () => {
      const f = fixtures["wechseln"];
      if (!f?.stems) return;
      const verb = buildVerbInput("wechseln", f);
      const computed = computeConjugation(verb, endings);
      const mismatches = compareTenses(computed, f.wiktionary);
      expect(mismatches.length).toBe(1);
      expect(mismatches[0]).toContain("imperative.du");
    });

    it("kennen — imperative uses long form in Wiktionary", () => {
      const f = fixtures["kennen"];
      if (!f?.stems) return;
      const verb = buildVerbInput("kennen", f);
      const computed = computeConjugation(verb, endings);
      const mismatches = compareTenses(computed, f.wiktionary);
      expect(mismatches.length).toBe(1);
      expect(mismatches[0]).toContain("imperative.du");
    });

    it("einladen — vowel change + e-insertion interaction", () => {
      const f = fixtures["einladen"];
      if (!f?.stems) return;
      const verb = buildVerbInput("einladen", f);
      const computed = computeConjugation(verb, endings);
      const mismatches = compareTenses(computed, f.wiktionary);
      expect(mismatches.length).toBeGreaterThan(0);
      expect(mismatches[0]).toContain("present.du");
    });
  });
});

// ============================================================
// Summary stats (informational)
// ============================================================

describe("Wiktionary comparison — coverage stats", () => {
  it("total fixture count", () => {
    expect(Object.keys(fixtures).length).toBe(77);
  });

  it("passing verbs count", () => {
    const passing = Object.entries(fixtures).filter(
      ([word]) => !ALL_EXPECTED_FAILURES.has(word),
    );
    expect(passing.length).toBe(67);
  });

  it("expected failure count", () => {
    const failing = Object.entries(fixtures).filter(
      ([word]) => ALL_EXPECTED_FAILURES.has(word),
    );
    expect(failing.length).toBe(10);
  });
});
