/**
 * Wiktionary comparison tests for verb-forms.js
 *
 * Tests computeConjugation() against conjugation tables extracted
 * directly from the German Wiktionary (de-extract.jsonl).
 *
 * Fixtures: tests/fixtures/wiktionary-verbs.json (77 verbs)
 * Generated by: scripts/extract-verb-fixtures.js
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { computeConjugation } from "../src/utils/verb-forms.js";
import type { ConjugationTable, VerbStems, VerbEndingsFile, PersonForms, ImperativeForms } from "../types/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const endings: VerbEndingsFile = JSON.parse(
  readFileSync(join(ROOT, "data/rules/verb-endings.json"), "utf-8"),
);

interface WiktionaryConjugation {
  present?: Partial<PersonForms>;
  preterite?: Partial<PersonForms>;
  subjunctive1?: Partial<PersonForms>;
  subjunctive2?: Partial<PersonForms>;
  imperative?: Partial<ImperativeForms>;
  participle1?: string;
  participle2?: string;
}

interface VerbFixture {
  word: string;
  conjugation_class: string | null;
  stems?: VerbStems;
  past_participle: string | null;
  separable: boolean;
  prefix: string | null;
  wiktionary: WiktionaryConjugation;
  inconsistent_cells?: string[];
}

type FixtureMap = Record<string, VerbFixture>;

const fixtures: FixtureMap = JSON.parse(
  readFileSync(join(ROOT, "tests/fixtures/wiktionary-verbs.json"), "utf-8"),
);

// ============================================================
// Expected failures -- verbs that our rules-based engine cannot
// handle without special-case code. Documented here so the test
// suite stays green while clearly showing what's not covered.
// ============================================================

/**
 * Truly irregular verbs -- their conjugation patterns don't follow
 * any regular class (weak/strong/mixed). These are stored as
 * conjugation_class: "irregular" in actual word files with full
 * conjugation tables. computeConjugation returns stored forms as-is.
 * Tested separately below to verify the passthrough works.
 */
const TRULY_IRREGULAR: Set<string> = new Set([
  "sein",     // bin/bist/ist -- completely suppletive
  "haben",    // hast/hat -- irregular present
  "werden",   // wirst/wird -- irregular present
  "wissen",   // weiss/weisst -- praeteritopraesentia
  "k\u00f6nnen",   // kann/kannst -- modal
  "m\u00fcssen",   // muss/musst -- modal
  "sollen",   // soll/sollst -- modal
  "wollen",   // will/willst -- modal
  "d\u00fcrfen",   // darf/darfst -- modal
  "m\u00f6gen",    // mag/magst -- modal
]);

/**
 * Weak imperative -e elision -- Wiktionary prefers the short form
 * (kauf!, hoer!) while our engine produces the full form (kaufe!, hoere!).
 * Both are grammatically correct in modern German.
 *
 * NOTE: The runtime validator (validateConjugation) now accepts both forms,
 * so these verbs pass validation. But the strict comparison here still
 * detects the difference for documentation purposes.
 */
const IMPERATIVE_E_ELISION: Set<string> = new Set([
  "kaufen",   // kaufe! vs kauf!
  "h\u00f6ren",    // hoere! vs hoer!
  "reden",    // rede! vs red!
  "sagen",    // sage! vs sag!
  "glauben",  // glaube! vs glaub!
  "fragen",   // frage! vs frag!
  "spielen",  // spiele! vs spiel!
]);

/**
 * Other individual edge cases not yet handled by the engine.
 */
const OTHER_KNOWN_ISSUES: Set<string> = new Set([
  "wechseln", // imperative: wechsle! vs wechsele! (Wiktionary uses long form)
  "kennen",   // imperative: kenn! vs kenne! (Wiktionary uses long form)
]);

const ALL_EXPECTED_FAILURES: Set<string> = new Set([
  ...IMPERATIVE_E_ELISION,
  ...OTHER_KNOWN_ISSUES,
]);

// ============================================================
// Helpers
// ============================================================

interface VerbInput {
  word: string;
  conjugation_class: string | null;
  stems?: VerbStems;
  past_participle: string | null;
  separable: boolean;
  prefix: string | null;
  conjugation?: ConjugationTable;
}

/**
 * Build a verb input object for computeConjugation.
 * For truly irregular verbs, passes conjugation_class: "irregular"
 * with the Wiktionary table as stored conjugation (matching how
 * actual word files store them).
 */
function buildVerbInput(word: string, f: VerbFixture): VerbInput {
  if (TRULY_IRREGULAR.has(word)) {
    return {
      word: f.word,
      conjugation_class: "irregular",
      conjugation: f.wiktionary as ConjugationTable,
      separable: f.separable,
      prefix: f.prefix,
      past_participle: f.past_participle,
    };
  }
  return {
    word: f.word,
    conjugation_class: f.conjugation_class,
    stems: f.stems,
    past_participle: f.past_participle,
    separable: f.separable,
    prefix: f.prefix,
  };
}

/**
 * Compare computed conjugation against Wiktionary forms.
 * Skips cells listed in `skipCells` (e.g., "subjunctive2.ich")
 * which are known Wiktionary-internal inconsistencies detected
 * by the majority-vote stem extraction.
 */
function compareTenses(computed: ConjugationTable, wiktionary: WiktionaryConjugation, skipCells: string[] = []): string[] {
  const skip = new Set(skipCells);
  const mismatches: string[] = [];
  const tenses = ["present", "preterite", "subjunctive1", "subjunctive2"] as const;

  for (const tense of tenses) {
    const wikiTense = wiktionary[tense];
    if (!wikiTense) continue;
    for (const [person, form] of Object.entries(wikiTense)) {
      if (skip.has(`${tense}.${person}`)) continue;
      const computedTense = computed[tense] as unknown as Record<string, string>;
      if (form && computedTense?.[person] !== form) {
        mismatches.push(
          `${tense}.${person}: "${computedTense?.[person]}" vs "${form}"`,
        );
      }
    }
  }

  if (wiktionary.imperative) {
    for (const [person, form] of Object.entries(wiktionary.imperative)) {
      if (skip.has(`imperative.${person}`)) continue;
      const computedImp = computed.imperative as unknown as Record<string, string>;
      if (form && computedImp?.[person] !== form) {
        mismatches.push(
          `imperative.${person}: "${computedImp?.[person]}" vs "${form}"`,
        );
      }
    }
  }

  if (wiktionary.participle1 && computed.participle1 !== wiktionary.participle1) {
    mismatches.push(
      `participle1: "${computed.participle1}" vs "${wiktionary.participle1}"`,
    );
  }
  if (wiktionary.participle2 && computed.participle2 !== wiktionary.participle2) {
    mismatches.push(
      `participle2: "${computed.participle2}" vs "${wiktionary.participle2}"`,
    );
  }

  return mismatches;
}

// ============================================================
// Tests: verbs that should pass (including irregular + sibilant)
// ============================================================

describe("Wiktionary comparison -- passing verbs", () => {
  const passingVerbs: [string, VerbFixture][] = Object.entries(fixtures).filter(
    ([word]) => !ALL_EXPECTED_FAILURES.has(word),
  );

  it.each(passingVerbs)("%s -- matches Wiktionary forms", (word: string, f: VerbFixture) => {
    const verb = buildVerbInput(word, f);
    const computed: ConjugationTable = computeConjugation(verb, endings);
    const mismatches = compareTenses(computed, f.wiktionary, f.inconsistent_cells || []);
    expect(mismatches, mismatches.join("; ")).toEqual([]);
  });
});

// ============================================================
// Tests: documented expected failures
// ============================================================

describe("Wiktionary comparison -- expected failures (documented)", () => {
  describe("weak imperative -e elision (both forms are correct)", () => {
    for (const word of IMPERATIVE_E_ELISION) {
      it(`${word} -- mismatch is only in imperative.du`, () => {
        const f = fixtures[word];
        if (!f?.stems) return;
        const verb = buildVerbInput(word, f);
        const computed: ConjugationTable = computeConjugation(verb, endings);
        const mismatches = compareTenses(computed, f.wiktionary);
        // Should only disagree on imperative
        expect(mismatches.length).toBe(1);
        expect(mismatches[0]).toContain("imperative.du");
      });
    }
  });

  describe("other individual edge cases", () => {
    it("wechseln -- imperative uses long form in Wiktionary", () => {
      const f = fixtures["wechseln"];
      if (!f?.stems) return;
      const verb = buildVerbInput("wechseln", f);
      const computed: ConjugationTable = computeConjugation(verb, endings);
      const mismatches = compareTenses(computed, f.wiktionary);
      expect(mismatches.length).toBe(1);
      expect(mismatches[0]).toContain("imperative.du");
    });

    it("kennen -- imperative uses long form in Wiktionary", () => {
      const f = fixtures["kennen"];
      if (!f?.stems) return;
      const verb = buildVerbInput("kennen", f);
      const computed: ConjugationTable = computeConjugation(verb, endings);
      const mismatches = compareTenses(computed, f.wiktionary);
      expect(mismatches.length).toBe(1);
      expect(mismatches[0]).toContain("imperative.du");
    });
  });
});

// ============================================================
// Summary stats (informational)
// ============================================================

describe("Wiktionary comparison -- coverage stats", () => {
  it("total fixture count", () => {
    expect(Object.keys(fixtures).length).toBe(86);
  });

  it("passing verbs count", () => {
    const passing = Object.entries(fixtures).filter(
      ([word]) => !ALL_EXPECTED_FAILURES.has(word),
    );
    expect(passing.length).toBe(77);
  });

  it("expected failure count", () => {
    const failing = Object.entries(fixtures).filter(
      ([word]) => ALL_EXPECTED_FAILURES.has(word),
    );
    expect(failing.length).toBe(9);
  });
});
