#!/usr/bin/env node

/**
 * Batching consistency test for gloss translation.
 *
 * Verifies that batched calls produce equivalent translations to single-item calls,
 * and that both agree with the ground-truth gloss_en values already stored in the
 * word JSON files (generated by translate-glosses.js).
 *
 * Three modes are tested per provider:
 *   A) single   -- one item per call, translate-glosses.js format (plain text response)
 *   B) batched  -- all items in one call, compare-models.js format (JSON array, hash IDs)
 *   C) stored   -- existing gloss_en values from the word JSON files (ground truth)
 *
 * Usage:
 *   node scripts/test-gloss-batching.ts                       # default: lm-studio/sauerkraut
 *   node scripts/test-gloss-batching.ts --provider ollama
 *   node scripts/test-gloss-batching.ts --provider openai
 *   node scripts/test-gloss-batching.ts --batch-size 3        # partial batches
 *   node scripts/test-gloss-batching.ts --no-cache            # skip cache, force fresh API calls
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { createHash } from "crypto";
import { callLLM, retryWithBackoff, parseProviderArgs, getDefaultModel, extractJSON } from "./lib/llm.js";
import { WORD_SYSTEM_PROMPT as SINGLE_SYSTEM_PROMPT, WORD_SYSTEM_PROMPT_BATCH_IDS, WORD_SYSTEM_PROMPT_BATCH_PLAIN } from "./lib/prompts.js";
import { stripReferences } from "./lib/references.js";
import type { LLMResponse, LLMProvider } from "../types/llm.js";
import type { Word, Sense } from "../types/word.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// ── CLI ──────────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const { provider: PROVIDER, model: MODEL } = parseProviderArgs(args);
const EFFECTIVE_PROVIDER: string = args.includes("--provider") ? PROVIDER : "lm-studio";
const batchSizeIdx = args.indexOf("--batch-size");
const BATCH_SIZE: number | null = batchSizeIdx !== -1
  ? parseInt(args[batchSizeIdx + 1], 10)
  : null; // null = all items in one call
const NO_CACHE: boolean = args.includes("--no-cache");

// ── Models that cannot reliably produce JSON output ───────────────────────────
// These use plain-text mode: no jsonSchema, one-translation-per-line batch format.

const PLAIN_MODE_MODELS: Set<string> = new Set([
  "tower-plus-9b-mlx",
]);

function isPlainMode(modelName: string): boolean {
  return PLAIN_MODE_MODELS.has(modelName);
}

// ── Batch system prompt (imported from lib/prompts.js) ───────────────────────

const BATCH_SYSTEM_PROMPT: string = WORD_SYSTEM_PROMPT_BATCH_IDS;

// Plain-text batch prompt for models that can't produce JSON (e.g. tower-plus-9b-mlx).
const PLAIN_BATCH_SYSTEM_PROMPT: string = WORD_SYSTEM_PROMPT_BATCH_PLAIN;

// ── Interfaces ───────────────────────────────────────────────────────────────

interface SingleTranslation {
  translation: string;
}

interface BatchTranslationItem {
  id: string;
  translation: string;
}

interface BatchTranslationResult {
  translations: BatchTranslationItem[];
}

interface FixtureItem {
  id: string;
  text: string;
  word: string;
  pos: string;
  gloss: string;
  cleanGloss: string;
  stored: string | null;
  storedModel: string | null;
}

interface CacheEntry {
  translation: string;
  text: string;
}

// ── JSON schemas ─────────────────────────────────────────────────────────────

const SINGLE_SCHEMA: Record<string, unknown> = {
  type: "object",
  properties: {
    translation: { type: "string" },
  },
  required: ["translation"],
  additionalProperties: false,
};

const BATCH_SCHEMA: Record<string, unknown> = {
  type: "object",
  properties: {
    translations: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id:          { type: "string" },
          translation: { type: "string" },
        },
        required: ["id", "translation"],
        additionalProperties: false,
      },
    },
  },
  required: ["translations"],
  additionalProperties: false,
};

// ── Content-hash IDs (same as compare-models.js) ─────────────────────────────

function glossPromptId(text: string): string {
  return createHash("sha256").update(text).digest("hex").slice(0, 8);
}

// ── Test fixtures: load from word JSON files ──────────────────────────────────

const FIXTURE_FILES: string[] = [
  "nouns/Bank_geldinstitut.json",
  "nouns/Bank_sitz.json",
  "nouns/Tisch.json",
];

function loadFixtures(): FixtureItem[] {
  const items: FixtureItem[] = [];
  for (const relPath of FIXTURE_FILES) {
    const filePath = join(ROOT, "data", "words", relPath);
    if (!existsSync(filePath)) {
      console.warn(`Warning: Fixture not found: ${relPath} -- skipping`);
      continue;
    }
    const data = JSON.parse(readFileSync(filePath, "utf-8")) as Word;
    const fileSlug = relPath.replace(/\.json$/, "").replace(/[^a-z0-9]/gi, "_").toLowerCase();
    for (let i = 0; i < (data.senses || []).length; i++) {
      const sense: Sense = data.senses[i];
      if (!sense.gloss) continue;
      const cleanGloss = stripReferences(sense.gloss);
      if (cleanGloss.length < 5) continue;

      const base = `word="${data.word}", pos="${data.pos}"`;
      const phraseType = (data as unknown as Record<string, unknown>).phrase_type as string | undefined;
      const typeClause = phraseType ? `, phrase_type="${phraseType}"` : "";
      const text = `${base}${typeClause}, gloss="${cleanGloss}"`;

      items.push({
        id: `${fileSlug}_${i}`,
        text,
        word: data.word,
        pos: data.pos,
        gloss: sense.gloss,
        cleanGloss,
        stored: sense.gloss_en ?? null,   // ground truth from previous translate-glosses run
        storedModel: sense.gloss_en_model ?? null,
      });
    }
  }
  return items;
}

// ── Cache ─────────────────────────────────────────────────────────────────────

const CACHE_DIR: string = join(ROOT, "data", "raw", "llm-compare-cache", "batching-test");

function cacheKey(mode: string, itemId: string, text: string): string {
  const textHash = createHash("sha256").update(text).digest("hex").slice(0, 8);
  return join(CACHE_DIR, `${mode}_${itemId}_${textHash}.json`);
}

function readCache(mode: string, itemId: string, text: string): string | null {
  if (NO_CACHE) return null;
  const p = cacheKey(mode, itemId, text);
  if (!existsSync(p)) return null;
  try {
    const entry = JSON.parse(readFileSync(p, "utf-8")) as CacheEntry;
    return entry.translation;
  } catch { return null; }
}

function writeCache(mode: string, itemId: string, text: string, translation: string): void {
  if (!existsSync(CACHE_DIR)) mkdirSync(CACHE_DIR, { recursive: true });
  const p = cacheKey(mode, itemId, text);
  writeFileSync(p, JSON.stringify({ translation, text }));
}

// ── Mode A: single-item calls (translate-glosses.js style) ───────────────────

async function translateSingle(items: FixtureItem[], providerKey: string, modelName: string): Promise<Record<string, string>> {
  const results: Record<string, string> = {};
  const plain = isPlainMode(modelName);
  const llmOptions = {
    provider: providerKey as LLMProvider, model: modelName, maxTokens: 64, temperature: 0.2,
    ...(plain ? {} : { jsonSchema: SINGLE_SCHEMA }),
  };

  for (const item of items) {
    const cached = readCache("single", item.id, item.text);
    if (cached) { results[item.id] = cached; continue; }

    const response: LLMResponse = await retryWithBackoff(
      () => callLLM(SINGLE_SYSTEM_PROMPT, item.text, llmOptions),
      2, 1000
    );

    let translation: string;
    if (plain) {
      translation = response.content.trim().split("\n")[0].trim().replace(/\.$/, "");
    } else {
      try {
        const parsed = extractJSON(response.content) as SingleTranslation | null;
        translation = (parsed?.translation ?? response.content).trim().split("\n")[0].trim().replace(/\.$/, "");
      } catch {
        translation = response.content.trim().split("\n")[0].trim().replace(/\.$/, "");
      }
    }
    results[item.id] = translation;
    writeCache("single", item.id, item.text, translation);

    await new Promise<void>(r => setTimeout(r, 50));
  }

  return results;
}

// ── Mode B: batched calls (compare-models.js style) ───────────────────────────

function buildBatchPrompt(batch: FixtureItem[]): string {
  const lines: string[] = [
    `Translate ${batch.length} German gloss(es) to English.`,
    `Treat each entry as completely independent -- do not let one entry influence another.\n`,
  ];
  for (const item of batch) {
    lines.push(`[${glossPromptId(item.text)}] ${item.text}`);
  }
  lines.push(
    `\nReturn a JSON object with a "translations" array of exactly ${batch.length} items: ` +
    `{"translations":[{"id":"the-hash-from-above","translation":"..."}, ...]}`
  );
  return lines.join("\n");
}

function buildPlainBatchPrompt(batch: FixtureItem[]): string {
  const lines: string[] = [
    `Translate ${batch.length} German gloss(es) to English.`,
    `Treat each entry as completely independent -- do not let one entry influence another.\n`,
  ];
  for (let i = 0; i < batch.length; i++) {
    lines.push(`${i + 1}. ${batch[i].text}`);
  }
  lines.push(`\nOutput exactly ${batch.length} lines -- one English equivalent per line, in order.`);
  return lines.join("\n");
}

async function translateBatched(items: FixtureItem[], providerKey: string, modelName: string, batchSize: number | null): Promise<Record<string, string>> {
  const results: Record<string, string> = {};
  const plain = isPlainMode(modelName);
  const size = batchSize ?? items.length;
  const llmOptions = {
    provider: providerKey as LLMProvider, model: modelName,
    maxTokens: size * 64, temperature: 0.2,
    ...(plain ? {} : { jsonSchema: BATCH_SCHEMA }),
  };
  const chunks: FixtureItem[][] = [];
  for (let i = 0; i < items.length; i += size) chunks.push(items.slice(i, i + size));

  for (const chunk of chunks) {
    const uncached = chunk.filter(it => {
      const cached = readCache("batched", it.id, it.text);
      if (cached) { results[it.id] = cached; return false; }
      return true;
    });

    if (uncached.length === 0) continue;

    const response: LLMResponse = await retryWithBackoff(
      () => callLLM(
        plain ? PLAIN_BATCH_SYSTEM_PROMPT : BATCH_SYSTEM_PROMPT,
        plain ? buildPlainBatchPrompt(uncached) : buildBatchPrompt(uncached),
        { ...llmOptions, maxTokens: uncached.length * 64 }
      ),
      2, 1000
    );

    if (plain) {
      // Parse one-per-line: numbered "1. translation" or bare lines
      const lines = response.content.trim().split("\n")
        .map(l => l.replace(/^\d+\.\s*/, "").trim())
        .filter(l => l.length > 0);
      uncached.forEach((item, idx) => {
        const translation = lines[idx];
        if (translation) {
          results[item.id] = translation;
          writeCache("batched", item.id, item.text, translation);
        }
      });
    } else {
      let parsed: BatchTranslationItem[];
      try {
        const raw = extractJSON(response.content) as BatchTranslationResult | BatchTranslationItem[] | Record<string, unknown>;
        if (Array.isArray(raw)) {
          parsed = raw as BatchTranslationItem[];
        } else if (raw && typeof raw === "object" && "translations" in raw) {
          parsed = (raw as BatchTranslationResult).translations;
        } else {
          const inner = Object.values(raw).find(v => Array.isArray(v)) as BatchTranslationItem[] | undefined;
          parsed = inner ?? [];
        }
      } catch (err) {
        console.error(`  Warning: Batch parse failed: ${err instanceof Error ? err.message : String(err)}`);
        console.error(`  Raw: ${response.content.slice(0, 200)}`);
        continue;
      }

      const hashToId: Record<string, string> = Object.fromEntries(uncached.map(it => [glossPromptId(it.text), it.id]));
      for (const entry of parsed) {
        const realId = hashToId[String(entry.id)];
        if (realId && entry.translation) {
          results[realId] = entry.translation;
          const item = uncached.find(it => it.id === realId);
          if (item) writeCache("batched", realId, item.text, entry.translation);
        }
      }
    }

    await new Promise<void>(r => setTimeout(r, 100));
  }

  return results;
}

// ── Comparison helpers ────────────────────────────────────────────────────────

function normalize(s: string | null | undefined): string {
  return (s ?? "").toLowerCase().trim().replace(/[()]/g, "").replace(/\s+/g, " ");
}

/** Rough equivalence: exact, or one is a parenthetical qualifier of the other */
function roughlyEqual(a: string | null | undefined, b: string | null | undefined): boolean {
  const na = normalize(a);
  const nb = normalize(b);
  if (na === nb) return true;
  // "bench sports" ≈ "bench" or "bench (sports)"
  if (na.startsWith(nb + " ") || nb.startsWith(na + " ")) return true;
  if (na.startsWith(nb) && na[nb.length] === " ") return true;
  if (nb.startsWith(na) && nb[na.length] === " ") return true;
  return false;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const model = MODEL || getDefaultModel(EFFECTIVE_PROVIDER);
  const providerLabel = `${EFFECTIVE_PROVIDER}/${model}`;
  const items = loadFixtures();

  if (items.length === 0) {
    console.error("No fixtures found -- check that data/words/nouns/Bank*.json and Tisch.json exist.");
    process.exit(1);
  }

  console.log(`Provider:   ${providerLabel}`);
  console.log(`Fixtures:   ${items.length} senses (${FIXTURE_FILES.join(", ")})`);
  console.log(`Batch size: ${BATCH_SIZE ?? `all ${items.length} at once`}`);
  if (NO_CACHE) console.log(`Cache:      disabled`);
  console.log();

  // Run both modes
  console.log("Running mode A -- single items (translate-glosses format)...");
  const singleStart = Date.now();
  const singleResults = await translateSingle(items, EFFECTIVE_PROVIDER, model);
  const singleTime = ((Date.now() - singleStart) / 1000).toFixed(1);
  console.log(`  done in ${singleTime}s`);

  console.log("Running mode B -- batched (compare-models format, hash IDs)...");
  const batchStart = Date.now();
  const batchedResults = await translateBatched(items, EFFECTIVE_PROVIDER, model, BATCH_SIZE);
  const batchTime = ((Date.now() - batchStart) / 1000).toFixed(1);
  console.log(`  done in ${batchTime}s`);
  console.log();

  // Print comparison table
  const COL = { word: 22, stored: 22, single: 22, batched: 22 };
  const pad = (s: string | null | undefined, n: number): string => String(s ?? "(none)").slice(0, n).padEnd(n);

  console.log(
    `${"WORD/SENSE".padEnd(COL.word)}  ` +
    `${"STORED (ground truth)".padEnd(COL.stored)}  ` +
    `${"SINGLE".padEnd(COL.single)}  ` +
    `${"BATCHED".padEnd(COL.batched)}  ` +
    `S~ST  B~ST  S~B`
  );
  console.log("\u2500".repeat(COL.word + COL.stored + COL.single + COL.batched + 30));

  let singleVsStored = 0;
  let batchedVsStored = 0;
  let singleVsBatched = 0;
  let storedAvailable = 0;

  for (const item of items) {
    const stored  = item.stored;
    const single  = singleResults[item.id];
    const batched = batchedResults[item.id];

    const ss = stored ? (roughlyEqual(single, stored) ? "\u2713" : "\u2717") : "\u2013";
    const bs = stored ? (roughlyEqual(batched, stored) ? "\u2713" : "\u2717") : "\u2013";
    const sb = roughlyEqual(single, batched) ? "\u2713" : "\u2717";

    if (stored) {
      storedAvailable++;
      if (ss === "\u2713") singleVsStored++;
      if (bs === "\u2713") batchedVsStored++;
    }
    if (sb === "\u2713") singleVsBatched++;

    const label = `${item.word} [${item.id.split("_").pop()}]`;
    console.log(
      `${pad(label, COL.word)}  ` +
      `${pad(stored, COL.stored)}  ` +
      `${pad(single, COL.single)}  ` +
      `${pad(batched, COL.batched)}  ` +
      `${ss.padEnd(5)} ${bs.padEnd(5)} ${sb}`
    );
  }

  console.log();
  if (storedAvailable > 0) {
    console.log(`Single  vs stored:  ${singleVsStored}/${storedAvailable} (${Math.round(100 * singleVsStored / storedAvailable)}%)`);
    console.log(`Batched vs stored:  ${batchedVsStored}/${storedAvailable} (${Math.round(100 * batchedVsStored / storedAvailable)}%)`);
  }
  console.log(`Single  vs batched: ${singleVsBatched}/${items.length} (${Math.round(100 * singleVsBatched / items.length)}%)`);

  if (singleVsBatched < items.length) {
    console.log();
    console.log("Mismatches (single != batched):");
    for (const item of items) {
      const s = singleResults[item.id];
      const b = batchedResults[item.id];
      if (!roughlyEqual(s, b)) {
        console.log(`  ${item.word}  gloss: "${item.cleanGloss.slice(0, 60)}"`);
        console.log(`    single:  ${s}`);
        console.log(`    batched: ${b}`);
      }
    }
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
